import type { ShortcutAction, ShortcutCategory } from '../types/shortcuts';

export const SHORTCUT_ACTIONS: ShortcutAction[] = [
  { id: 'transport.playPause',   category: 'transport', label: 'Play / Pause',               defaultCombo: { code: 'Space' }, contexts: ['global'] },
  { id: 'transport.stop',        category: 'transport', label: 'Stop + Return to 0',         defaultCombo: { code: 'Enter' }, contexts: ['global'] },
  { id: 'transport.loop',        category: 'transport', label: 'Toggle Loop',                 defaultCombo: { code: 'KeyL' }, contexts: ['global'] },
  { id: 'transport.metronome',   category: 'transport', label: 'Toggle Metronome',            defaultCombo: { code: 'KeyK' }, contexts: ['global'] },
  { id: 'transport.record',      category: 'transport', label: 'Arm Focused Track / Toggle Record', defaultCombo: { code: 'KeyR' }, contexts: ['global'] },
  { id: 'transport.home',        category: 'transport', label: 'Jump to Start',               defaultCombo: { code: 'Home' }, contexts: ['global'] },
  { id: 'transport.end',         category: 'transport', label: 'Jump to End',                 defaultCombo: { code: 'End' }, contexts: ['global'] },
  { id: 'transport.nudgeLeft',   category: 'transport', label: 'Nudge Playhead Left',         defaultCombo: { code: 'ArrowLeft' }, contexts: ['timeline'] },
  { id: 'transport.nudgeRight',  category: 'transport', label: 'Nudge Playhead Right',        defaultCombo: { code: 'ArrowRight' }, contexts: ['timeline'] },
  { id: 'transport.punchToggle', category: 'transport', label: 'Toggle Punch In/Out',         defaultCombo: { code: 'KeyP', shift: true }, contexts: ['global'] },
  { id: 'transport.punchIn',     category: 'transport', label: 'Set Punch-In Point',          defaultCombo: { code: 'KeyI' }, contexts: ['global'] },
  { id: 'transport.punchOut',    category: 'transport', label: 'Set Punch-Out Point',         defaultCombo: { code: 'KeyO', shift: true }, contexts: ['global'] },
  { id: 'transport.captureMidi', category: 'transport', label: 'Capture MIDI',                defaultCombo: { code: 'KeyF' }, contexts: ['global'] },
  { id: 'transport.videoRecord', category: 'transport', label: 'Toggle Video Recording',      defaultCombo: { code: 'KeyV', mod: true, shift: true }, contexts: ['global'] },

  { id: 'clips.delete',          category: 'clips',     label: 'Delete Selected Clips',       defaultCombo: { code: 'Backspace' }, contexts: ['timeline'] },
  { id: 'clips.duplicate',       category: 'clips',     label: 'Duplicate Clip',              defaultCombo: { code: 'KeyD', mod: true }, contexts: ['timeline'] },
  { id: 'clips.split',           category: 'clips',     label: 'Split Clip at Playhead',      defaultCombo: { code: 'KeyS' }, contexts: ['timeline'] },
  { id: 'clips.selectAll',       category: 'clips',     label: 'Select All Clips',            defaultCombo: { code: 'KeyA', mod: true }, contexts: ['timeline'] },
  { id: 'clips.edit',            category: 'clips',     label: 'Edit Selected Clip',          defaultCombo: { code: 'KeyE' }, contexts: ['timeline'] },
  { id: 'clips.generate',        category: 'clips',     label: 'Generate Selected Clip',      defaultCombo: { code: 'Enter', mod: true }, contexts: ['timeline'] },
  { id: 'clips.toggleMute',      category: 'clips',     label: 'Toggle Clip Mute',            defaultCombo: { code: 'Digit0' }, contexts: ['timeline'] },
  { id: 'clips.enhance',         category: 'clips',     label: 'Enhance Selected Clip',       defaultCombo: { code: 'KeyE', shift: true }, contexts: ['timeline'] },
  { id: 'clips.copy',            category: 'clips',     label: 'Copy',                        defaultCombo: { code: 'KeyC', mod: true }, contexts: ['timeline', 'pianoRoll'] },
  { id: 'clips.cut',             category: 'clips',     label: 'Cut',                         defaultCombo: { code: 'KeyX', mod: true }, contexts: ['timeline', 'pianoRoll'] },
  { id: 'clips.paste',           category: 'clips',     label: 'Paste',                       defaultCombo: { code: 'KeyV', mod: true }, contexts: ['timeline', 'pianoRoll'] },

  { id: 'tracks.mute',           category: 'tracks',    label: 'Toggle Focused Track Mute',   defaultCombo: { code: 'KeyM' }, contexts: ['timeline', 'mixer', 'pianoRoll'] },
  { id: 'tracks.solo',           category: 'tracks',    label: 'Toggle Focused Track Solo',   defaultCombo: { code: 'KeyS', shift: true }, contexts: ['timeline', 'mixer', 'pianoRoll'] },
  { id: 'tracks.bypassEffects',  category: 'tracks',    label: 'Toggle Focused Track FX Bypass', defaultCombo: { code: 'KeyP' }, contexts: ['timeline', 'mixer', 'pianoRoll'] },
  { id: 'tracks.createGroup',    category: 'tracks',    label: 'Create Group Track',          defaultCombo: { code: 'KeyG', mod: true, shift: true }, contexts: ['timeline', 'mixer'] },
  { id: 'tracks.toggleCollapse', category: 'tracks',    label: 'Toggle Group Collapse',       defaultCombo: { code: 'KeyG', shift: true }, contexts: ['timeline'] },
  { id: 'tracks.delete',         category: 'tracks',    label: 'Delete Selected Tracks',      defaultCombo: { code: 'Backspace', mod: true }, contexts: ['timeline'] },
  { id: 'tracks.selectAll',      category: 'tracks',    label: 'Select All Tracks',           defaultCombo: { code: 'KeyA', mod: true }, contexts: ['timeline'] },

  { id: 'navigation.previousTrack', category: 'navigation', label: 'Focus Previous Track',   defaultCombo: { code: 'ArrowUp' }, contexts: ['timeline', 'mixer'] },
  { id: 'navigation.nextTrack',     category: 'navigation', label: 'Focus Next Track',       defaultCombo: { code: 'ArrowDown' }, contexts: ['timeline', 'mixer'] },

  { id: 'view.zoomIn',           category: 'view',      label: 'Zoom In',                     defaultCombo: { code: 'Equal', mod: true }, contexts: ['global'] },
  { id: 'view.zoomOut',          category: 'view',      label: 'Zoom Out',                    defaultCombo: { code: 'Minus', mod: true }, contexts: ['global'] },
  { id: 'view.zoomReset',        category: 'view',      label: 'Reset Zoom',                  defaultCombo: { code: 'Digit0', mod: true }, contexts: ['global'] },
  { id: 'view.zoomToSelection',  category: 'view',      label: 'Zoom to Selection',           defaultCombo: { code: 'KeyZ' }, contexts: ['timeline'] },
  { id: 'view.zoomToFit',        category: 'view',      label: 'Zoom to Fit Full Project',    defaultCombo: { code: 'KeyZ', shift: true }, contexts: ['timeline'] },
  { id: 'view.toggleSnap',       category: 'view',      label: 'Toggle Snap',                 defaultCombo: { code: 'KeyN' }, contexts: ['timeline'] },
  { id: 'view.toggleSessionView', category: 'view',     label: 'Toggle Session View',         defaultCombo: { code: 'Tab' }, contexts: ['global'] },

  { id: 'generation.silence',    category: 'generation', label: 'Generate from Silence',     defaultCombo: { code: 'KeyG', mod: true }, contexts: ['global'] },
  { id: 'generation.context',    category: 'generation', label: 'Generate from Context',     defaultCombo: { code: 'KeyG', mod: true, shift: true }, contexts: ['global'] },

  { id: 'panels.mixer',          category: 'panels',    label: 'Toggle Mixer',                defaultCombo: { code: 'KeyX' }, contexts: ['global'] },
  { id: 'panels.smartControls',  category: 'panels',    label: 'Toggle Smart Controls',       defaultCombo: { code: 'KeyB' }, contexts: ['global'] },
  { id: 'panels.library',        category: 'panels',    label: 'Toggle Library',              defaultCombo: { code: 'KeyY' }, contexts: ['global'] },
  { id: 'panels.loopBrowser',    category: 'panels',    label: 'Toggle Loop Browser',         defaultCombo: { code: 'KeyO' }, contexts: ['global'] },
  { id: 'panels.trackList',      category: 'panels',    label: 'Toggle Track List Rail',      defaultCombo: { code: 'KeyW' }, contexts: ['timeline'] },
  { id: 'panels.tempoLane',      category: 'panels',    label: 'Toggle Tempo Lane',           defaultCombo: { code: 'KeyT' }, contexts: ['global'] },
  { id: 'panels.arrangementMarkers', category: 'panels', label: 'Toggle Arrangement Markers', defaultCombo: { code: 'KeyA' }, contexts: ['global'] },
  { id: 'panels.generation',     category: 'panels',    label: 'Toggle AI Generation Panel',  defaultCombo: { code: 'KeyG' }, contexts: ['global'] },
  { id: 'panels.generationHistory', category: 'panels', label: 'Toggle Generation History Panel', defaultCombo: { code: 'KeyH' }, contexts: ['global'] },
  { id: 'panels.modelLibrary',   category: 'panels',    label: 'Toggle Model Library',        defaultCombo: { code: 'KeyM', shift: true }, contexts: ['global'] },
  { id: 'panels.strudel',        category: 'panels',    label: 'Toggle Strudel',              defaultCombo: { code: 'KeyU' }, contexts: ['global'] },
  { id: 'panels.aiAssistant',    category: 'panels',    label: 'Toggle AI Assistant',         defaultCombo: { code: 'Slash', mod: true }, contexts: ['global'] },
  { id: 'panels.clipInspector',  category: 'panels',    label: 'Toggle Clip Inspector',       defaultCombo: { code: 'KeyI', shift: true }, contexts: ['global'] },
  { id: 'view.autoScroll',        category: 'view',      label: 'Toggle Auto-Scroll',          defaultCombo: { code: 'KeyF', shift: true }, contexts: ['global'] },

  { id: 'project.new',           category: 'project',   label: 'New Project',                 defaultCombo: { code: 'KeyN', mod: true }, contexts: ['global'] },
  { id: 'project.open',          category: 'project',   label: 'Open Project List',           defaultCombo: { code: 'KeyO', mod: true }, contexts: ['global'] },
  { id: 'project.bounceInPlace', category: 'project',   label: 'Bounce Selected/Focused Track', defaultCombo: { code: 'KeyB', mod: true }, contexts: ['global'] },
  { id: 'project.settings',      category: 'project',   label: 'Open Generate Settings',      defaultCombo: { code: 'Comma', mod: true }, contexts: ['global'] },
  { id: 'project.export',        category: 'project',   label: 'Export',                      defaultCombo: { code: 'KeyE', mod: true, shift: true }, contexts: ['global'] },
  { id: 'project.addTrack',      category: 'project',   label: 'Add Track',                   defaultCombo: { code: 'KeyI', mod: true, shift: true }, contexts: ['global'] },
  { id: 'project.help',          category: 'project',   label: 'Keyboard Shortcuts Help',     defaultCombo: { code: 'Slash', shift: true }, contexts: ['global'] },

  { id: 'pianoRoll.delete',       category: 'pianoRoll', label: 'Delete Selected Notes',     defaultCombo: { code: 'Delete' }, contexts: ['pianoRoll'] },
  { id: 'pianoRoll.transposeUp',  category: 'pianoRoll', label: 'Transpose Up 1 Semitone',   defaultCombo: { code: 'ArrowUp', shift: true }, contexts: ['pianoRoll'] },
  { id: 'pianoRoll.transposeDown',category: 'pianoRoll', label: 'Transpose Down 1 Semitone', defaultCombo: { code: 'ArrowDown', shift: true }, contexts: ['pianoRoll'] },
  { id: 'pianoRoll.quantize',     category: 'pianoRoll', label: 'Quantize Selected Notes',   defaultCombo: { code: 'KeyQ' }, contexts: ['pianoRoll'] },
  { id: 'pianoRoll.quantizeOpts', category: 'pianoRoll', label: 'Quantize with Options',     defaultCombo: { code: 'KeyQ', mod: true }, contexts: ['pianoRoll'] },
  { id: 'pianoRoll.selectAll',    category: 'pianoRoll', label: 'Select All Notes',          defaultCombo: { code: 'KeyA', mod: true }, contexts: ['pianoRoll'] },

  { id: 'session.up',             category: 'session',   label: 'Select Previous Track Slot', defaultCombo: { code: 'ArrowUp' }, contexts: ['session'] },
  { id: 'session.down',           category: 'session',   label: 'Select Next Track Slot',     defaultCombo: { code: 'ArrowDown' }, contexts: ['session'] },
  { id: 'session.left',           category: 'session',   label: 'Select Previous Scene Slot', defaultCombo: { code: 'ArrowLeft' }, contexts: ['session'] },
  { id: 'session.right',          category: 'session',   label: 'Select Next Scene Slot',     defaultCombo: { code: 'ArrowRight' }, contexts: ['session'] },
  { id: 'session.launch',         category: 'session',   label: 'Launch Selected Clip',       defaultCombo: { code: 'Enter' }, contexts: ['session'] },
  { id: 'session.stop',           category: 'session',   label: 'Stop Selected Track',        defaultCombo: { code: 'Digit0' }, contexts: ['session'] },
  { id: 'session.delete',         category: 'session',   label: 'Delete Selected Clip',       defaultCombo: { code: 'Backspace' }, contexts: ['session'] },
  { id: 'session.duplicate',      category: 'session',   label: 'Duplicate Selected Clip',    defaultCombo: { code: 'KeyD', mod: true }, contexts: ['session'] },
];

export const SHORTCUT_ACTION_MAP: Record<string, ShortcutAction> = Object.fromEntries(
  SHORTCUT_ACTIONS.map((action) => [action.id, action]),
);

export const SHORTCUT_CATEGORIES: { id: ShortcutCategory; label: string }[] = [
  { id: 'transport', label: 'Transport' },
  { id: 'clips', label: 'Clips' },
  { id: 'tracks', label: 'Tracks' },
  { id: 'navigation', label: 'Navigation' },
  { id: 'view', label: 'View' },
  { id: 'generation', label: 'Generation' },
  { id: 'panels', label: 'Panels' },
  { id: 'project', label: 'Project' },
  { id: 'pianoRoll', label: 'Piano Roll' },
  { id: 'session', label: 'Session' },
];
