export const TIMELINE_MINIMAP_HEIGHT = 28;
export const TIMELINE_RULER_HEIGHT = 34;
export const ARRANGEMENT_MARKERS_HEIGHT = 20;
export const TEMPO_LANE_HEIGHT = 60;
export const TIME_SIGNATURE_LANE_HEIGHT = 36;
